data_rentgen/db/models/address.py
data_rentgen/db/models/dataset.py
data_rentgen/db/models/job.py
data_rentgen/db/models/location.py
data_rentgen/db/models/run.py
data_rentgen/db/repositories/base.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/output.py
data_rentgen/db/repositories/run.py
data_rentgen/server/services/lineage.py

* `search_vector` is not returned by any API call, exclude it from SELECT queries
* If depth>1, the same operation is first selected in `depth=3`, then operation_ids is passed to call with `depth=2` to select the same operation and its run/job. Avoid doing the same query twice.
* Input/output's `created_at` is always the same as operations's created at. So instead of user specified since/until, use min and max `created_at` of operations. This leads to searching data is a more narrow slice of a table.
* Add max limit for operation and run `created_at` field, to avoid scanning partitions there is no data for sure.
Each case is implemented in s separated commit, to simplify a review process.
(see [CONTRIBUTING.rst](https://github.com/MobileTeleSystems/data-rentgen/blob/develop/CONTRIBUTING.rs …

[DOP-19494] Optimize queries

---

data_rentgen/db/repositories/dataset.py
data_rentgen/db/repositories/dataset_symlink.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/job.py
data_rentgen/db/repositories/location.py
data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/output.py
data_rentgen/db/repositories/run.py
data_rentgen/server/services/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

Using `WHERE id IN (...)` syntax has a flaw - if there are different number of items in this list, SQLAlchemy will produce different SELECT queries, like:
```
... WHERE id IN (%(id1)s, %(id2)s)
... WHERE id IN (%(id1)s, %(id2)s, %id(3)s)
... WHERE id IN (%(id1)s, %(id2)s, %id(3)s, ..., %id(50)s)
```
This prevents SQLAlchemy from using already compiled query from the cache.
Instead replace it with syntax:
```
... WHERE id = ANY (%(ids)s)
```
In this case `ids` is a list of values, passed directly to Postgres, and thus fixes cache misses.
Also add test cases when lineage is requested for an object with no relations/inputs/outputs.
Previously some of those were failing. 

[DOP-19494] Replace id IN () with id = ANY ()

---

data_rentgen/server/api/v1/router/__init__.py
data_rentgen/server/api/v1/router/dataset.py
data_rentgen/server/api/v1/router/job.py
data_rentgen/server/api/v1/router/operation.py
data_rentgen/server/api/v1/router/run.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/dataset.py
data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/services/lineage.py
data_rentgen/server/utils/lineage_response.py
poetry.lock
pyproject.toml
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_get_lineage_request_validators.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

Split `/v1/lineage` into four different endpoints, for each entity (dataset, operation, run, job)
Remove query class from pydantic request schemas for lineage (https://github.com/fastapi/fastapi/releases/tag/0.115.0).
[DOP-20059]

[DOP-20048] Split lineage endpoint

---

data_rentgen/server/schemas/v1/job.py
tests/test_server/test_get_jobs.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py
tests/test_server/test_search/test_job.py

There is a field `job.type` in database table, but it was missing in REST API response schema. Fixed.

[DOP-20137] Fix missing job.type in API responses

---

data_rentgen/db/repositories/base.py
data_rentgen/db/repositories/dataset.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/job.py
data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/output.py
data_rentgen/db/repositories/run.py
data_rentgen/server/api/v1/router/dataset.py
data_rentgen/server/api/v1/router/job.py
data_rentgen/server/api/v1/router/operation.py
data_rentgen/server/api/v1/router/run.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/dataset.py
data_rentgen/server/schemas/v1/job.py
data_rentgen/server/schemas/v1/operation.py
data_rentgen/server/schemas/v1/pagination.py
data_rentgen/server/schemas/v1/run.py
tests/test_server/test_datasets/test_search_datasets.py
tests/test_server/test_jobs/test_search_jobs.py
tests/test_server/test_lineage/test_get_lineage_request_validators.py
tests/test_server/test_operations/test_get_operations.py
tests/test_server/test_operations/test_get_operations_by_id.py
tests/test_server/test_operations/test_get_operations_by_run_id.py
tests/test_server/test_runs/test_get_runs.py
tests/test_server/test_runs/test_get_runs_by_job_id.py
tests/test_server/test_runs/test_get_runs_by_parent_run_id.py
tests/test_server/test_runs/test_search_runs.py

* Merge endpoints like `/v1/datasets` and `/v1/datasets/search` to one `/v1/datasets` endpoint
* Make query options for `/v1/runs` and `/v1/operations` less strict - if user passed multiple field, add both of them to search query instead of raising an error. It's up to user if given filters make any sense.

[DOP-20055] Merge /entries with /entries/search

---

data_rentgen/server/schemas/v1/run.py
tests/test_server/test_datasets/test_search_datasets.py
tests/test_server/test_jobs/test_search_jobs.py
tests/test_server/test_runs/test_search_runs.py

Since now, field `since` is mandatory if user passed `search_query` to `GET /v1/runs`. This allows narrowing access to specific partition of `run` table, instead of scanning all partitions.
This is especially useful while searching by query which appears in most of rows of the table.
Also added negative test cases for search endpoints.

[DOP-20849] Make since field mandatory in runs search

---

data_rentgen/consumer/extractors/__init__.py
data_rentgen/consumer/extractors/batch.py
data_rentgen/consumer/extractors/dataset.py
data_rentgen/consumer/extractors/job.py
data_rentgen/consumer/handlers.py
data_rentgen/db/repositories/location.py
data_rentgen/dto/dataset.py
data_rentgen/dto/dataset_symlink.py
data_rentgen/dto/input.py
data_rentgen/dto/job.py
data_rentgen/dto/location.py
data_rentgen/dto/operation.py
data_rentgen/dto/output.py
data_rentgen/dto/run.py
data_rentgen/dto/schema.py
data_rentgen/dto/user.py
tests/test_consumer/test_extractors/test_extractors_batch_airflow.py
tests/test_consumer/test_extractors/test_extractors_batch_spark.py
tests/test_consumer/test_extractors/test_extractors_dataset.py
tests/test_consumer/test_extractors/test_extractors_interaction.py
tests/test_consumer/test_extractors/test_extractors_job.py
tests/test_consumer/test_extractors/test_extractors_operation.py
tests/test_consumer/test_extractors/test_extractors_run.py

Make consumer fetching a list of OpenLineage events instead of fetching them one-by-one:
* Add DTO property `unique_key` and method `merge`. This allows tracking multiple versions of the same DTO, and then merge into one DTO having all the non-null fields. For example, all RunDTOs with same id are merged into one RunDTO with non-null created_at and ended_at, and so on.
* Add `BatchExtractResult` class which tracks each type of DTO, merges old items with new ones, and then allows to iterate other merged items.
* Move all extraction logic from consumer to dedicated function `extract_batch`. It iterates other list of OpenLineage events (e.g. sequence of STARTED+RUNNING+SUCCESS) into a final one (SUCCESS with started_at + ended_at + ...).
* Combine all DB logic inside consumer into one …

[DOP-20958] Consume events in batches

---

data_rentgen/consumer/handlers.py
data_rentgen/db/repositories/dataset.py
data_rentgen/db/repositories/dataset_symlink.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/job.py
data_rentgen/db/repositories/location.py
data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/output.py
data_rentgen/db/repositories/run.py

* All evens for operation and related inputs & outputs are always send to the same Kafka topic - OpenLineage's default key is `parentRunId or runId`, and user can override it only for the entire Spark session, not specific operations. So instead of saving them row-by-row, we can generate one `INSERT ON CONFLICT UPDATE` statement with all data in the batch.
For other entity types, it is not safe to bulk inserts as it may introduce deadlocks between parallel consumer workers.
* Sometimes parallel workers may insert new addresses to the location. This case wasn't covered with a proper lock, so the entire batch may fail due to conflict. Fixed.
Benchmarks were run in the same environment (4 FastStream workers, 4 Kafka partitions) and the amount of data (239k events, 632MB with ZSTD …

[DOP-20958] Insert operations, inputs & outputs in one statement

---

data_rentgen/db/repositories/location.py
data_rentgen/server/api/v1/router/__init__.py
data_rentgen/server/api/v1/router/location.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/location.py
tests/test_server/fixtures/factories/location.py
tests/test_server/test_locations/test_get_locations.py
tests/test_server/test_locations/test_get_locations_by_id.py
tests/test_server/test_locations/test_search_locations.py
tests/test_server/utils/enrich.py

Add `/v1/location` endpoint. Filter by location ids, location type and search_vector. Search include Location.name and Address.url.
[DOP-20048]

[DOP-20048] add GET /v1/location endpoint

---

data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/services/lineage.py
data_rentgen/server/utils/lineage_response.py
tests/test_server/fixtures/factories/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_get_lineage_request_validators.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py
tests/test_server/utils/stats.py

* Set `direction=BOTH` as default in all API entpoints.
* Instead of test like `with_direction_both` make tests `with_direction_downstream` & `with_direction_upstream`. By default, tests do not set `direction` at all, so `BOTH` is used.
* Remove lineage tests which passed multiple options to API, like `with_until_granularity` or `with_until_direction`. Instead, make separated tests `with_until`, `with_granularity`. The only exception is `with_depth_granularity` because these ones are deeply related.
* Drop `relation_stats` and `relation_stats_by_operations` helpers - first one is not used anymore, second one is replaced with just accessing the original `input` or `output` object (`granularity=OPERATION` returns original inputs & outputs, without aggregation).
* During rewrite, I've …

[DOP-21531] Set default direction to BOTH

---

data_rentgen/db/models/input.py
data_rentgen/db/models/output.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/output.py
data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/utils/lineage_response.py
pyproject.toml
tests/test_server/fixtures/factories/input.py
tests/test_server/fixtures/factories/output.py
tests/test_server/fixtures/factories/schema.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

- `Schema` add as Pydantic model to `LineageOutputRelationV1` and `LineageInputRelationV1`.
- add `_add_schema()` to `input` and `ouput` repositories. Which calls if `granularity=='OPERATION'`.
Mb it's not best way, but I am not sure where else we have `inputs\outputs` + `granularity`.
[DOP-20062]

[DOP-20062] Add schema to relations in a lineage response

---

data_rentgen/server/services/lineage.py
tests/test_server/fixtures/factories/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

Case - there is a full lineage graph like this:
```
/ dataset3
dataset1 - job1 -> current_dataset -> job2 -> dataset2
dataset4 /
```
And we call `GET /v1/datasets/lineage` for `current_dataset` with `direction=BOTH` and `depth>1`.
We expect this endpoint to receive only nodes & relations which are a part of either input chain of `current_dataset`, or output chain, e.g.:
```
dataset1 - job1 -> current_dataset -> job2 -> dataset2
```
But instead we receive full graph.
What changed:
* Respect `direction=BOTH` only for building the first level lineage (`job1 -> current_dataset -> job2`). While getting lineage for nested nodes (job1, job2), use more specific direction (`direction=UPSTREAM` for job1, `direction=DOWNSTREAM` for job2).
* Add `branchy_lineage` fixture creating a complex graph like …

[DOP-21295] Do not include unrelated datasets to lineage with depth>1

---

data_rentgen/server/schemas/v1/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

According to OpenLineage spec, dataset `schema` facet has only `fields` attribute:
https://github.com/OpenLineage/OpenLineage/blob/2130ab9fa46cda0a02db13b5b7b265f1bbfe8b51/spec/facets/SchemaDatasetFacet.json#L40
Other attributes, like `name`, `type`, `description` are present only in nested `field`.
Change response schema accordingly and update tests.

[DOP-21572] Remove unused fields from schema response

---

data_rentgen/db/models/input.py
data_rentgen/db/models/output.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/output.py
data_rentgen/db/repositories/schema.py
data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/services/lineage.py
pyproject.toml
tests/test_server/fixtures/factories/input.py
tests/test_server/fixtures/factories/lineage.py
tests/test_server/fixtures/factories/output.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py
tests/test_server/utils/merge.py

* If all inputs/outputs within the Run or Job had the same `schema_id`, return this schema in API response with `granularity=RUN` or `JOB`. If any input/output has a different schema, return `None`, as we cannot properly merge them.
* Same for `Output.type`. Previously if different Outputs within the same Run or Job had different types, we returned multiple relations, each with different `type` value. Now we try to preserve original type, but if there are any Output with different type, replace it with `None`.
* For most tests use fixed `scheme_id` and `type=APPEND`, and check that schema and type are returned in API.
* Add tests for case then each input/output has a different schema/type.
* Also add tests with empty stats for Dataset, Job and Run lineage (previously it was implemented …

[DOP-21572] Return interaction schema with granularity=RUN|JOB

---

data_rentgen/server/schemas/v1/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py

Added `id` field to `schema` response. Although users cannot fetch schema by its id, this fields allows to check whether 2 schemas are equal without converting them to the same canonical format (e.g. json with sorted keys).

[DOP-21572] Add id field to IO schema

---

data_rentgen/consumer/extractors/__init__.py
data_rentgen/consumer/extractors/batch.py
data_rentgen/consumer/extractors/dataset.py
data_rentgen/consumer/extractors/input.py
data_rentgen/consumer/extractors/output.py
data_rentgen/dto/dataset.py
tests/test_consumer/test_extractors/test_extractors_batch_spark.py
tests/test_consumer/test_extractors/test_extractors_dataset.py
tests/test_consumer/test_extractors/test_extractors_interaction.py
tests/test_consumer/test_handlers/test_runs_handler_spark.py

- All datasets now extrac in one method `extract_io_dataset`. It's return updated DatasetDTO, with new fields:
- `dataset_symlinks: list[DatasetDTO]` - store all symlinks.
- symlink_type: - store type type of connection. Used for `TABLE` type.
*MB It's better add new DTO for symlinks.`*
- Dataset connect with it symlinks via function `connect_dataset_with_symlinks() -> list[DatasetSymlinkDTO]`
- Remove `extract_dataset_aliases` - it is not used
[DOP-20054]

[DOP-20054] Add swap  dataset and it's symlink(hive) for hdfs

---

data_rentgen/consumer/extractors/run.py
data_rentgen/consumer/openlineage/run_facets/airflow.py
tests/test_consumer/test_extractors/test_extractors_batch_airflow.py
tests/test_consumer/test_extractors/test_extractors_run.py
tests/test_consumer/test_handlers/test_runs_handler_airflow.py
tests/test_consumer/test_openlineage/test_run_event_airflow.py

- Add airflow dag owner as user in case `owner != 'airflow'`
[DOP-22750]

[DOP-22750] Add owner parsing for airflow run events

---

data_rentgen/db/migrations/versions/2025-01-09_56f5a3f9442a_create_custom_user_properties.py
data_rentgen/db/migrations/versions/2025-01-09_61ea5edad711_create_custom_properties.py
data_rentgen/db/models/__init__.py
data_rentgen/db/models/custom_properties.py
data_rentgen/db/models/custom_user_properties.py

- Create table custom_properties and custom_user_properties
- Add postgres extension btree-gist
[DOP-22582]

[DOP-22582] Create custom_properties and custom_user_properties tables

---

data_rentgen/server/providers/auth/keycloak_provider.py

Missed redirect_uri for auth request

[DOP-23122] add redirect_uri to auth request

---

.pre-commit-config.yaml
data_rentgen/db/migrations/versions/2025-02-03_f017d4c58658_create_analytic_view.py
data_rentgen/db/scripts/refresh_analytic_views.py
docs/reference/database/index.rst
docs/reference/database/views_cli.rst
pyproject.toml

[DOP-22585] Move views creation to migration
[DOP-22585]

[DOP-22585] Move views creation to migration

---

data_rentgen/consumer/extractors/batch.py
data_rentgen/consumer/extractors/dataset.py
data_rentgen/db/models/custom_user_properties.py

* Do not call `dto.merge(new_dto)` if `dto` and `new_dto` are the same object. This is small optimization, used mostly for locations and datasets, as they are reused as nested fields for other DTOs (inputs, outputs and so on).
* Simplify s bit logic for `extract_dataset_and_symlinks` - do not call `extract_dataset` multiple times for the same input.
* SQLAlchemy shows warning about unknown property `server_defaults`, it should be `server_default`

[DOP-22401] Small fixes and optimizations

---

data_rentgen/db/migrations/env.py
data_rentgen/db/migrations/versions/2025-02-04_15c0a22b8566_create_column_lineage.py
data_rentgen/db/models/__init__.py
data_rentgen/db/models/column_lineage.py
data_rentgen/db/models/dataset_column_relation.py
docs/reference/database/structure.rst

Added 2 tables to store column lineage:
* `dataset_column_relation` - tuple of `(source_column, target_column, type)` with common `fingerprint` value (hash of specific relation set).
* `column_lineage` - tuple of `(operation, source_dataset, target_dataset, fingerprint)`.
This combination requires the least amount of space, as relations between columns remain the same between multiple operations/runs/jobs, and sometimes even between datasets.
For example, for 2.6M rows/4.9GB of raw events in Kafka (=1.2M operations/230MB), column lineage requires only:
* `dataset_column_relation` - 14.6k rows, 3.2MB
* `column_lineage` - 52.9k rows, 13MB
Storing column lineage as flat table `(operation, source_dataset, target_dataset, source_column, target_column, type)` requires much more space - 805k …

[DOP-22364] Add column lineage tables

---

data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/output.py
data_rentgen/server/api/v1/router/operation.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/operation.py
data_rentgen/server/services/__init__.py
data_rentgen/server/services/operation.py
docs/changelog/next_release/158.breaking.rst
pyproject.toml
tests/test_server/test_operations/test_get_operations_by_id.py
tests/test_server/test_operations/test_get_operations_by_run_id.py

Changed the response schema of `GET /operations` to include inputs & outputs statistics. This is useful to show in list of operations within run.
Don't change response for lineage, as it includes inputs & outputs are distinct relations.

[DOP-22578] Return statistics in GET /operations

---

data_rentgen/db/repositories/dataset.py
data_rentgen/db/repositories/job.py
data_rentgen/server/api/v1/router/location.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/location.py
data_rentgen/server/services/__init__.py
data_rentgen/server/services/location.py
docs/changelog/next_release/160.breaking.rst
tests/test_server/test_locations/test_get_locations.py
tests/test_server/test_locations/test_get_locations_by_id.py
tests/test_server/test_locations/test_patch_locations.py
tests/test_server/test_locations/test_search_locations.py

Changed the response schema of `GET /locations` and `PATCH /locations/:id` to include dataset & job statistics. This is useful to show in list of locations, or to show/hide tabs with datasets/jobs list on LocationShow page.

[DOP-22578] Return statistics in GET /locations

---

data_rentgen/server/api/v1/router/dataset.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/dataset.py
data_rentgen/server/services/__init__.py
data_rentgen/server/services/dataset.py
docs/changelog/next_release/161.breaking.rst
tests/test_server/test_datasets/test_get_datasets.py
tests/test_server/test_datasets/test_get_datasets_by_id.py
tests/test_server/test_datasets/test_search_datasets.py

Changed the response schema of `GET /datasets` to match other endpoints (#158, #159, #160, #162). For now there is no statistics for dataset, but it can be added later (e.g. inputs/outputs stats within last day/week/month) without breaking backward compatibility.

[DOP-22578] Change response schema of GET /datasets

---

data_rentgen/server/api/v1/router/job.py
data_rentgen/server/schemas/v1/__init__.py
data_rentgen/server/schemas/v1/job.py
data_rentgen/server/services/__init__.py
data_rentgen/server/services/job.py
docs/changelog/next_release/162.breaking.rst
tests/test_server/test_jobs/test_get_jobs.py
tests/test_server/test_jobs/test_get_jobs_by_id.py
tests/test_server/test_jobs/test_search_jobs.py

Changed the response schema of `GET /jobs` to match other endpoints (#158, #159, #160, #161). For now there is no statistics for job, but it can be added later (e.g. number of runs since last day, week, month) without breaking backward compatibility.

[DOP-22578] Change response schema of GET /jobs

---

tests/test_server/test_datasets/test_get_datasets.py
tests/test_server/test_datasets/test_get_datasets_by_id.py
tests/test_server/test_datasets/test_search_datasets.py
tests/test_server/test_jobs/test_get_jobs.py
tests/test_server/test_jobs/test_get_jobs_by_id.py
tests/test_server/test_jobs/test_search_jobs.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py
tests/test_server/test_locations/test_get_locations.py
tests/test_server/test_locations/test_get_locations_by_id.py
tests/test_server/test_locations/test_patch_locations.py
tests/test_server/test_locations/test_search_locations.py
tests/test_server/test_operations/test_get_operations_by_id.py
tests/test_server/test_operations/test_get_operations_by_run_id.py
tests/test_server/test_runs/test_get_runs_by_id.py
tests/test_server/test_runs/test_get_runs_by_job_id.py
tests/test_server/test_runs/test_get_runs_by_parent_run_id.py
tests/test_server/test_runs/test_search_runs.py
tests/test_server/utils/convert_to_json.py
tests/test_server/utils/merge.py

Most of test lines are JSON output examples, and there are A LOT of them. It is very cumbersome to apply any changes to these tests (like change API schema) because this requires a lot of copy-pasting.
Instead, implement simple functions to convert SQLAlchemy model to JSON representation, and use for all API tests instead of raw JSON examples.
This reduces number of lines a lot (-4k). Also fixes flaky tests caused by datetime isoformat comparison, like `2025-01-01T11:22:33.000000Z != 2025-01-01T11:22:33Z`.

[DOP-23867] Implement model -> json converter for tests

---

data_rentgen/consumer/extractors/dataset.py
docs/changelog/next_release/175.improvement.rst
docs/quickstart/setup_spark.rst
tests/test_consumer/test_extractors/test_extractors_batch_spark.py
tests/test_consumer/test_extractors/test_extractors_dataset.py

Add regular expresion to remove partition like part of the name in file storages.
`name="/app/warehouse/somedb.db/sometable/business_dt=2025-01-01/reg_id=99"`
`name="/app/warehouse/somedb.db/sometable`
[DOP-22776]
* [ x Keep the change as small as possible

[DOP-22776] Strip partitions from dataset name

---

data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/output.py
data_rentgen/server/services/lineage.py
data_rentgen/server/utils/lineage_response.py
docs/changelog/next_release/171.feature.rst
tests/test_server/test_lineage/test_column_lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py
tests/test_server/test_lineage/test_job_lineage.py
tests/test_server/test_lineage/test_operation_lineage.py
tests/test_server/test_lineage/test_run_lineage.py
tests/test_server/utils/convert_to_json.py

This is required to show sum of operations within run, and sum of runs within job in the lineage graph:
Instead of calling `list_by_run_ids(granularity="RUN") + list_by_JOB_ids(granularity="JOB")`, call `list_by_run_ids(granularity="RUN") + list_by_RUN_ids(granularity="JOB")`. Otherwise lineage graph may include inputs & outputs of job with other datasets, not actually used by selected `run_id` or `operation_id`.
This logic can be implemented on UI side, but the code is quite ugly, so I've decided that it's better to move it to backend.

[DOP-23921] Include sum inputs & outputs to lineage response

---

data_rentgen/db/repositories/dataset_column_relation.py
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/output.py

Operations, inputs and outputs are created with predefined `id` field, so we don't actually need `RETURNING ...` in insert queries. This optimization reduces the amount of data read from DB, but not very much - for 1.6 mil events read IO reduced from 475MB to 455MB.

[DOP-23708] Do not use RETURNING if result is ignored

---

data_rentgen/consumer/extractors/__init__.py
data_rentgen/consumer/extractors/batch.py
data_rentgen/consumer/extractors/column_lineage.py
data_rentgen/consumer/extractors/dataset.py
data_rentgen/consumer/extractors/job.py
data_rentgen/consumer/extractors/operation.py
data_rentgen/consumer/extractors/run.py
tests/test_consumer/test_handlers/test_runs_handler_spark.py

Before this change, `extract_column_lineage` took about 13% of consumer run time.
After this change it tooks only 2%, due to cached result of parsing OpenLineageDataset -> DatasetDTO:
This reduces the percent of time consumer spends inside `run_event_handler` from 23.3% to 14.3%.
Also I've get rid of `isinstance(object, PydanticModel)` because this is an expensive operation, and we don't need this check at all in some cases.
As a bonus, previously `extract_dataset_with_symlinks` replaced HDFS dataset with Hive table, but column lineage connected HDFS source -> target dataset instead of Hive source -> target dataset, as it haven't resolved any symlinks. Now this is fixed, and column lineage is in sync with inputs/outputs.
(see [CONTRIBUTING.rst](https://github.com/MobileTeleSystems/data-ren …

[DOP-23708] Cache datasets for column lineage extraction

---

data_rentgen/consumer/extractors/batch.py
data_rentgen/dto/column_lineage.py
data_rentgen/dto/dataset.py
data_rentgen/dto/dataset_column_relation.py
data_rentgen/dto/dataset_symlink.py
data_rentgen/dto/input.py
data_rentgen/dto/job.py
data_rentgen/dto/location.py
data_rentgen/dto/output.py
data_rentgen/dto/schema.py

Currently `BatchExtractionResult._add` already can handle case then existing batch item is exactly the same as new item (using `var1 is var2`). But this optimization is not applied if objects are different with exactly the same fields value, which is quite common for `extract_*` functions.
Add 2 small optimizations here:
* If location, dataset, job, schema DTO method `.merge(old, new)` received object with exactly the same field values, return existing object instead of constructing new one.
* For nested DTOs reuse existing items from batch result.
This reduced amount of time spent in `add_input` from 3% to 1.3%, not very much:

[DOP-23708] Improve caching inside BatchExtractionResult

---

data_rentgen/db/repositories/operation.py
data_rentgen/db/repositories/run.py
data_rentgen/server/schemas/v1/run.py
docs/changelog/next_release/184.feature.rst
tests/test_server/test_operations/test_get_operations_by_id.py
tests/test_server/test_operations/test_get_operations_by_run_id.py
tests/test_server/test_runs/test_get_runs.py
tests/test_server/test_runs/test_get_runs_by_id.py
tests/test_server/test_runs/test_get_runs_by_job_id.py
tests/test_server/test_runs/test_get_runs_by_parent_run_id.py

`ORDER BY {primary key columns} (ASC|DESC) LIMIT N` is quite effective operation, so we don't have to filter runs by something else. Same for `COUNT`.

[DOP-24369] Make search_query param optional in GET /v1/runs

---

.pre-commit-config.yaml
data_rentgen/db/repositories/input.py
data_rentgen/db/repositories/output.py
data_rentgen/server/api/v1/router/operation.py
data_rentgen/server/api/v1/router/run.py
data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/services/lineage.py
data_rentgen/server/services/operation.py
data_rentgen/server/services/run.py
data_rentgen/server/utils/lineage_response.py
docs/changelog/next_release/185.improvement.rst
tests/test_server/utils/convert_to_json.py
tests/test_server/utils/merge.py

Change logic for output/input dataset schema in lineage response.
Add types of schema in reponse 'EXACT_MATCH' and 'LATEST_KNOWN'.
'EXACT_MATCH' - when last and first(order by `created_at` ascending) schema_ids are the same.
'LATEST_KNOWN' - when last and first are not the same, in this case last schema_id will return.
[DOP-23711]

[DOP-23711] Change returning schema in lineage response

---

data_rentgen/db/migrations/versions/2025-03-17_976168ee4f16_remove_partitions_from_dataset_names.py
docs/changelog/next_release/188.improvement.rst

Migration to remove partition part from dataset names.
Migration has next steps:
- Add `new` datasets with names without partitions and location_ids if there are doesn't exists already.
- fill temp table `dataset_migration` as map (old_id -> new_id)
- Update related tables (output, input, column_lineage, symlinks)
- Delete datasets with old_ids from `dataset`
- Remove dublicates from `input` (on current state of db dublicates are present only in `input`)
[DOP-24159]

[DOP-24159] add migration to remove partitons from dataset names

---

data_rentgen/server/services/lineage.py
docs/changelog/next_release/189.improvement.rst

Before - dataset symlinks are always included into lineage graph:
After - dataset symlinks are included only of they have some input or output:
This reduces visual noise.

[DOP-24570] Exclude dataset symlinks with no inputs/outputs

---

.github/workflows/test.yml
.pre-commit-config.yaml
Makefile
data_rentgen/db/scripts/clean_partitions.py
docs/changelog/next_release/254.improvement.rst
docs/reference/database/clean_data_cli.rst
docs/reference/database/index.rst

Add script for cleaning old partitions.
The ``clean_partitions.py`` script helps automate the cleanup of old table partitions based on a specified keep-after date. It supports different commands for dry runs, detaching partitions, removing data, and truncating partitions.
It's automatically inditifies partitioned tables and their granularity.
[DOP-26065]

[DOP-26065] add script to clean old partitions

---

data_rentgen/db/repositories/io_dataset_relation.py
docs/changelog/next_release/261.bugfix.rst
tests/test_server/fixtures/factories/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py

Add check that `SELECT input.dataset_id, output.dataset_id FROM input JOIN output` doesn't return the same dataset in both columns, as this is completely useless information for `granularity=DATASET`.

[DOP-27661] Exclude self-references from granularity=DATASET

---

.gitlab-ci.yml
data_rentgen/dto/dataset.py
data_rentgen/dto/dataset_column_relation.py
data_rentgen/dto/dataset_symlink.py
data_rentgen/dto/input.py
data_rentgen/dto/job.py
data_rentgen/dto/job_type.py
data_rentgen/dto/location.py
data_rentgen/dto/operation.py
data_rentgen/dto/output.py
data_rentgen/dto/pagination.py
data_rentgen/dto/run.py
data_rentgen/dto/schema.py
data_rentgen/dto/sql_query.py
data_rentgen/dto/user.py
tests/test_consumer/test_extractors/test_extractors_operation_airflow.py
tests/test_consumer/test_extractors/test_extractors_run_airflow.py

`dataclass(slots=True)` reduces memory usage and speeds up attribute access a little bit.
This conflicts with `@cached_property` (it requires class to have `__dict__` attribute), so I've replaced it with regular field initialized within constructor. This doesn't work with `ColumnLineageDTO` because it's `fingerprint` depends on list of `DatasetColumnRelationDTO` which is dynamic.
Before - extraction takes 38.27% of al consumer method calls:
After - 37.36%

Use dataclass(slots=True) on DTOs

---

.gitlab-ci.yml
data_rentgen/consumer/extractors/batch_extraction_result.py
data_rentgen/consumer/extractors/impl/spark.py
data_rentgen/db/repositories/run.py
data_rentgen/dto/job.py
docs/changelog/next_release/263.improvement.rst
tests/test_consumer/test_extractors/fixtures/spark_raw.py
tests/test_consumer/test_extractors/test_extractors_batch_spark.py

Sometimes Spark application-level STARTED event is emitted with `job.name=unknown` and no information about Spark session (applicationId, urls, user name and so on).
https://github.com/OpenLineage/OpenLineage/pull/3848 implements a workaround - Spark command events now have `spark_applicationDetails` facet as well, so we can extract this information from other events emitted by integration.
Current PR implements extraction of Spark application data for all event types, and adds tests for this behavior.

[DOP-27406] Add workaround for Spark sessions with name=unknown

---

data_rentgen/db/repositories/io_dataset_relation.py
docs/changelog/next_release/264.bugfix.rst
tests/test_server/fixtures/factories/lineage.py
tests/test_server/test_lineage/test_dataset_lineage.py

Joining inputs & outputs by `run_id` may return false positives on lineage graph with `granulaity=DATASET`. Instead join by `operation_id`.

[DOP-26804] Make granularity=DATASET lineage more precise

---

data_rentgen/consumer/extractors/impl/unknown.py
data_rentgen/consumer/openlineage/run_facets/__init__.py
data_rentgen/consumer/openlineage/run_facets/data_rentgen_operation.py
data_rentgen/consumer/openlineage/run_facets/data_rentgen_run.py
docs/changelog/next_release/265.feature.rst
tests/test_consumer/test_extractors/test_extractors_operation_unknown.py
tests/test_consumer/test_extractors/test_extractors_run_unknown.py

* Added new facets `dataRentgen_run` and `dataRentgen_operation` with fields resembling Run and Operation DTOs.
* Added logic of extracting these fields to `UnknownExtractor`, with tests.
These facets allow informing DataRentgen that it should create either Operation, Run or both from specific runEvent, which is important for custom integrations.
This doesn't include documentation, it will be added later.

[DOP-26993] Add custom DataRentgen facets

---

data_rentgen/openlineage/run.py
data_rentgen/openlineage/run_facets/parent_run.py
data_rentgen/server/schemas/v1/lineage.py
data_rentgen/server/schemas/v1/operation.py
data_rentgen/server/schemas/v1/run.py
data_rentgen/utils/__init__.py
data_rentgen/utils/uuid.py
tests/test_server/test_lineage/test_get_lineage_request_validators.py

Using `pydantic.UUID7` class for OpenLineage and FastAPI request annotations instead of PlainValidator. This allows to check UUID version on pydantic-core (Rust) side, and pass UUID version to Swagger:

[DOP-25468] Validate UUID version using Pydantic UUID7 class

---

data_rentgen/db/repositories/dataset.py
data_rentgen/server/api/v1/router/dataset.py
data_rentgen/server/api/v1/router/job.py
data_rentgen/server/api/v1/router/location.py
data_rentgen/server/api/v1/router/operation.py
data_rentgen/server/api/v1/router/run.py
data_rentgen/server/api/v1/router/tag.py
data_rentgen/server/schemas/v1/dataset.py
data_rentgen/server/schemas/v1/job.py
data_rentgen/server/schemas/v1/location.py
data_rentgen/server/schemas/v1/operation.py
data_rentgen/server/schemas/v1/run.py
data_rentgen/server/schemas/v1/tag.py
data_rentgen/server/services/dataset.py
docs/changelog/next_release/294.improvement.rst
tests/test_server/test_datasets/test_get_datasets_by_id.py
tests/test_server/test_operations/test_get_operations.py
tests/test_server/test_operations/test_get_operations_by_run_id.py
tests/test_server/test_runs/test_get_runs.py
tests/test_server/test_runs/test_get_runs_by_job_id.py
tests/test_server/test_runs/test_get_runs_by_parent_run_id.py
tests/test_server/test_runs/test_search_runs.py

- Add filter 'location_id' for dataset pagination query
- Change type of `DatasetPaginationQuery` from `Depends()` to `Query()`. With `Depends` the `model_config = {'extra': 'forbiden'}` doesn't work. Same fix for all entities (`Job`, `Run`, ....)
[DOP-22531]

[DOP-22531] Add location_id filter for dataset
